### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by webflo**
Please add a composer.json to the repo to allow installation via composer. Thanks!

### CODE REVIEW

**Comment by Berdir** [comment]
Note that development for flag moved back to d.o, the repository should be updated for that. So you will have to post patches there.

**Comment by webflo** [comment]
Thanks! Maybe we should update the project page on github.

**Comment by socketwench** [comment]
Done. I've created an "empty" branch and set it as the default.

**Comment by webflo** [comment]
Thanks!

**Pull request closed without merging**
