### PR TITLE
Fix for flag add page form UI regression.

### PR DESCRIPTION
**Pull request by socketwench**
PR for https://github.com/socketwench/flag-drupal8/issues/115

The tests are currently broken for the Confirm form and Field Entry link types.

### CODE REVIEW

**Comment by joachim-n** [comment]
This appears to have a bunch of unrelated changes in FlaggingAccessController.php.

**Comment by Berdir** [comment]
I opened a pull request for your pull request: https://github.com/socketwench/flag-drupal8/pull/124 ;)

Can't push directly into this.

**Comment by Berdir** [comment]
I think you need to merge or rebase from master again, to get the PHPCS fix.

**Comment by joachim-n** [comment]
This will need to be handled on d.org now -- I've pulled the code to an 8.x branch there.

**Comment by socketwench** [comment]
Moved to Drupal.org: https://www.drupal.org/node/2410005

**Pull request closed without merging**
